version: '3.8'

services:
  eureka-server:
    image: eurekaserver
    build:
      context: ../eureka-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - eureka-net

  chefe-service:
    image: chefeservice
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - eureka-net

networks:
  eureka-net: